version: "3"

services:
  app:
    networks:
      - default
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  default:
    external: true
    name: apache_kafka_default
